// While Loop...

let counter = 0;
while(counter < 10) {                                  // while("check condition"){"do something..."}  loop
    console.log(counter, "You're awesome :)");
    counter++;
}

let counterOne = 10;
while(counterOne > 0) {                                  
    console.log(counterOne, "You're crazy :)");
    counterOne--;
}



// Do While Loop...

let counterTwo = 0;
do {                                                                        // do{"first"} while("check later...");  loop
    console.log(counterTwo, "Why is the most important question...");
    counterTwo++;
} while (counterTwo <= 10);



/*
    >_ You're not gonna use while loop everytime, you'll use for loops most times.
    >_ You can't re-assign a variable in Javascript as python..
    >_ 
*/