console.log(process.platform);


// The Show: Kerris Dorsey

/* 
Billie Eilish - Happier Than Ever, when we all fall asleep where do we go, dont smile at me

    Bored
    lovely
    everything i wanted

*/

/*
girl in red - if i could make it go quiet

    rue
    midnight love
    I'll call you mine

*/

// Justice - Justin Bieber
// Entergalactic - Kid Cudi
// METRO BOOMIN PRESENTS SPIDER-MAN: ACROSS THE SPIDER-VERSE

/*
Post Malone - AUSTIN

    Circles
    Sunflower
    Too Cool To Die

*/
